### ISSUE TITLE
Breaker related stuff

### ISSUE THREAD

**Issue by genestrashcan** [age-series/ElectricalAge#173] opened 2019-08-01 20:03 UTC
The current EA Breakers need a lot of work done to fix issues with them, currently when you purposefully create a short circuit with a ground rod with any voltage cable, the breaker does not trip and the wire breaks or explodes if explosions are on, and if it does trip, the wire still explodes or melts afterwards (if explosions are off)

breakers should instantly trip when a ground rod touches any lower voltage wire when a short circuit happens and the wire should not explode or melt after the breaker trips in some instances

higher voltages such a 3400 v should use fuses or bigger breakers designed to break a high voltage arc if a short circuit happens

the customizable Breakers should be able to be customized to trip at any voltage, amperage, and wattage. 

AF/GF Breakers should be added eventually that would detect a wire arcing / ground faults from switch boards in homes.

**Smaller breakers should be implemented to be installed in panels / switch boards installed in homes, they should come in preset amperage ratings like 15a, 20a, 30a, 40a, 50a, etc like real life box store breakers.**

Instead of explosions at lower voltages, during a short circuit without proper protection, wires should be designed so when a short circuit happens, within a matter of seconds the insulation on the wire starts emitting smoke particles, then it melts so the becomes exposed as a live bare wire and begins grounds out to and electrifying any conductive surfaces like ground or especially metal blocks if their attached to something conductive like dirt, rock, or sand, or metal, during a short circuit the wire should heat up like a toaster element and glow red hot and melt until it breaks somewhere and also starts fires depending on the material it is installed on, if it is on conductive surfaces like metal it would continue to short circuit until the weakest point broke causing fires. If it is High voltage wire attached to some surface that gets a short circuit, its insulation should melt and then it should arc all over the place and start fires left and right and lead to a massive fire. this could be very bad in a power plant without proper protections in place making quite a mess, here is a video showing what happens to tools when their used to short circuit a low voltage transformer - https://www.youtube.com/watch?v=ut5DXxK1dvk

effects should be implemented to create particles to make a arc flash in minecraft if a ground rod is put on a live wire or something is wired wrong causing a short circuit at low voltages, and at higher voltages generate a big arc that continues for a few seconds.

with higher voltage wires on poles without proper spacing away from the ground that are running many amps and high voltage through them, during a short circuit they should melt and start burning and also create some massive arcs like the stuff in this video below - https://www.youtube.com/watch?v=gOT8jx4jEzM

also with t1 and t2 poles, if their wired up, if the pole or wire on the pole is broken or it hangs too low to ground and arcs and the wire melts and breaks, the wires from the other poles connected to it should fall to the ground like the minecraft rope and create a short circuit that could be quite a fireworks show if proper protection is not implemented on the network to prevent it.

**Comment by jrddunbr** [comment] 2019-08-02 01:50
Most of the things you are complaining about are problems with the MNA and hypothetically would be solved with some intermediate steps to check before doing the heat calculations.

Said step could be CPU intensive. It's also why the diodes suck, and everything else is pretty much delayed by a tick.

The difference between the breakers is marginal, in real life it's through various detection methods regarding EMF and thermal properties of metals to detect current, but in the case of Electrical Age, we just get the current and temperature readings from the simulator, so different types of breakers is mostly irrelevant I think. I suppose that there may be a possibility for a slow blow and a fast blow breaker, that may be possible, basing it on the thermal simulation rather than the current simulation and vice versa.

I like the idea of different ratings of breakers. I think it would be relatively easy to do.

The rest of your ideas are duplicated in #75 or something that will come later.

**Comment by jrddunbr** [comment] 2020-01-07 02:38
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by jrddunbr** [comment] 2023-08-06 02:33
Duplicate of #166

**Closed by jrddunbr** 2023-08-06 02:33 UTC
Labels: enhancement, model work, texture work, code work
